// <auto-generated />
using System;
using FamilyPromiseApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyPromiseApp.Migrations
{
    [DbContext(typeof(FamilyPContext))]
    [Migration("20231211171213_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("FamilyPromiseApp.Models.Case", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentSituation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomesticViolenceHistory")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthChallenge")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsEmployed")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsHoused")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferringAgency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Substance")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakenBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportMethod")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Case", (string)null);
                });

            modelBuilder.Entity("FamilyPromiseApp.Models.IntakeModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdultAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdultCellPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AdultDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdultEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdultName")
                        .HasColumnType("TEXT");

                    b.Property<int>("AdultNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdultWorkPhone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arrest")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrestLoc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Assets")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bankruptcy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellPhoneNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChildDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildGender")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildSchool")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Convictions")
                        .HasColumnType("TEXT");

                    b.Property<string>("DCF")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<int>("DateAdmitted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateToday")
                        .HasColumnType("TEXT");

                    b.Property<int>("Debts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAdd")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyFirst")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyLast")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployedWhere")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployerPhone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FatherChild")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Fired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HouseHoldChildrenExists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HouseHoldMemberExists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HouseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Income")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsEmployed")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsHoused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LengthOfEmploy")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parole")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParoleEmail")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParolePhone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Race")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason2")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecentHousing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferralAgency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationships")
                        .HasColumnType("TEXT");

                    b.Property<int>("SSN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShelterBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceAbuse")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceIss")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakenByNow")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeNow")
                        .HasColumnType("TEXT");

                    b.Property<int>("Transportation1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transportation2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transportation3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unemployed")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkPhoneNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkStudy")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("IntakeModel", (string)null);
                });

            modelBuilder.Entity("FamilyPromiseApp.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdultAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdultCellPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AdultDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdultEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdultName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdultWorkPhone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhone")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChildDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<int?>("HouseHoldChildrenExist")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HouseHoldMemberExist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseHoldNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("FamilyPromiseApp.Models.Referral", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Referral", (string)null);
                });

            modelBuilder.Entity("FamilyPromiseApp.Models.Resource", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Resource", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
